CREATE DATABASE IF NOT EXISTS ecotrace;
USE ecotrace;

CREATE TABLE organisations (
    id INT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(255) NOT NULL,
     city VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);